<a href="https://colab.research.google.com/github/rocx320/MachineLearning/blob/main/2247226_ML_Lab3_Demonstrate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lab - 3 Demonstrate PCA for the following datasets**

**Name : Piyush Rai**

**Reg. No. 2247226**

#**Mobile price dataset**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('test.csv')

In [3]:
data.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   
1    0.8        191  ...  12        746       857  3895     6     0   
2    0.9        186  ...   4       1270      1366  2396    17    10   
3    0.5         96  ...  20        295      1752  3893    10     0   
4    0.5        108  ...  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  
1          7        1             0     0  
2         10        0             1     1  
3          7        1             1     0  
4          7        1             0     1  

[5 rows x 21 columns]

In [4]:
data.shape

(1000, 21)

**Display the dataset before and after Preprocessing**

In [5]:
data.isnull().sum()

id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
dtype: int64

In [6]:
data.describe()

id  battery_power         blue  clock_speed     dual_sim  \
count  1000.000000    1000.000000  1000.000000  1000.000000  1000.000000   
mean    500.500000    1248.510000     0.516000     1.540900     0.517000   
std     288.819436     432.458227     0.499994     0.829268     0.499961   
min       1.000000     500.000000     0.000000     0.500000     0.000000   
25%     250.750000     895.000000     0.000000     0.700000     0.000000   
50%     500.500000    1246.500000     1.000000     1.500000     1.000000   
75%     750.250000    1629.250000     1.000000     2.300000     1.000000   
max    1000.000000    1999.000000     1.000000     3.000000     1.000000   

                fc       four_g   int_memory        m_dep   mobile_wt  ...  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000  ...   
mean      4.593000     0.487000    33.652000     0.517500   139.51100  ...   
std       4.463325     0.500081    18.128694     0.280861    34.85155  ...   
min       0.000000     0.000000     2.000000     0.100000    80.00000  ...   
25%       1.000000     0.000000    18.000000     0.300000   109.75000  ...   
50%       3.000000     0.000000    34.500000     0.500000   139.00000  ...   
75%       7.000000     1.000000    49.000000     0.800000   170.00000  ...   
max      19.000000     1.000000    64.000000     1.000000   200.00000  ...   

                pc    px_height     px_width          ram         sc_h  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     10.054000   627.121000  1239.774000  2138.998000    11.995000   
std       6.095099   432.929699   439.670981  1088.092278     4.320607   
min       0.000000     0.000000   501.000000   263.000000     5.000000   
25%       5.000000   263.750000   831.750000  1237.250000     8.000000   
50%      10.000000   564.500000  1250.000000  2153.500000    12.000000   
75%      16.000000   903.000000  1637.750000  3065.500000    16.000000   
max      20.000000  1907.000000  1998.000000  3989.000000    19.000000   

              sc_w    talk_time      three_g  touch_screen         wifi  
count  1000.000000  1000.000000  1000.000000    1000.00000  1000.000000  
mean      5.316000    11.085000     0.756000       0.50000     0.507000  
std       4.240062     5.497636     0.429708       0.50025     0.500201  
min       0.000000     2.000000     0.000000       0.00000     0.000000  
25%       2.000000     6.750000     1.000000       0.00000     0.000000  
50%       5.000000    11.000000     1.000000       0.50000     1.000000  
75%       8.000000    16.000000     1.000000       1.00000     1.000000  
max      18.000000    20.000000     1.000000       1.00000     1.000000  

[8 rows x 21 columns]

In [7]:
# min-max normalization

from sklearn.preprocessing import MinMaxScaler

# Create an instance of MinMaxScaler
scaler = MinMaxScaler()

# Perform min-max normalization
normalized_dataset1 = scaler.fit_transform(data)

normalized_dataset1

array([[0.        , 0.36224149, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.001001  , 0.22748499, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.002002  , 0.87191461, 1.        , ..., 0.        , 1.        ,
        1.        ],
       ...,
       [0.997998  , 0.45697131, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.998999  , 0.68912608, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.51367578, 1.        , ..., 1.        , 0.        ,
        1.        ]])

**Display Covariance matrix**

In [8]:
covariance_matrix=np.cov(data)
covariance_matrix

array([[664680.77914286, 690320.34121429, 514726.96642857, ...,
        265013.48514286, 482495.20578571, 509730.02778571],
       [690320.34121429, 755755.68190476, 538157.25264286, ...,
        265737.01054762, 494439.31809524, 547980.54059524],
       [514726.96642857, 538157.25264286, 505788.64228571, ...,
        259359.59842857, 395552.97435714, 417550.36135714],
       ...,
       [265013.48514286, 265737.01054762, 259359.59842857, ...,
        184935.64047619, 258916.76045238, 261171.04645238],
       [482495.20578571, 494439.31809524, 395552.97435714, ...,
        258916.76045238, 427465.46190476, 435546.08440476],
       [509730.02778571, 547980.54059524, 417550.36135714, ...,
        261171.04645238, 435546.08440476, 463431.21690476]])

**Display Eigen Values and Eigen Vector**

In [9]:
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

In [10]:
eigenvalues

array([ 3.66744337e+08+0.00000000e+00j,  3.12873274e+07+0.00000000e+00j,
        1.10315443e+07+0.00000000e+00j,  5.25075766e+06+0.00000000e+00j,
        4.18780810e+06+0.00000000e+00j,  9.51086264e+04+0.00000000e+00j,
        1.65585651e+04+0.00000000e+00j,  2.22078584e+03+0.00000000e+00j,
        1.41456045e+03+0.00000000e+00j,  1.26393103e+03+0.00000000e+00j,
        4.84740542e+02+0.00000000e+00j,  4.25162984e+02+0.00000000e+00j,
        2.49848180e+02+0.00000000e+00j,  3.22980335e+01+0.00000000e+00j,
        1.54850283e+01+0.00000000e+00j,  1.33243348e+01+0.00000000e+00j,
        1.19510460e+01+0.00000000e+00j,  1.15109380e+01+0.00000000e+00j,
        5.05448565e+00+0.00000000e+00j,  4.67765367e+00+0.00000000e+00j,
       -1.52826918e-08+1.55003130e-08j, -1.52826918e-08-1.55003130e-08j,
        8.75725350e-09+1.85422402e-08j,  8.75725350e-09-1.85422402e-08j,
       -2.01343420e-08+0.00000000e+00j,  1.12398083e-08+0.00000000e+00j,
       -7.80559417e-09+6.79693432e-09j, -7.80559417

In [11]:
eigenvectors

array([[ 4.08174495e-02+0.00000000e+00j,  3.22481055e-02+0.00000000e+00j,
         6.43332775e-03+0.00000000e+00j, ...,
         1.47384935e-02+2.01937299e-03j, -2.71914562e-02+8.84168507e-03j,
        -2.71914562e-02-8.84168507e-03j],
       [ 4.22817448e-02+0.00000000e+00j,  5.19299167e-02+0.00000000e+00j,
         2.05038036e-02+0.00000000e+00j, ...,
         1.12406060e-03+7.28599011e-05j, -2.40290221e-03-2.16376379e-04j,
        -2.40290221e-03+2.16376379e-04j],
       [ 3.54937135e-02+0.00000000e+00j, -1.92149835e-02+0.00000000e+00j,
         1.92967654e-03+0.00000000e+00j, ...,
        -3.64388060e-03+5.19883080e-04j, -6.97964281e-05-2.57677188e-03j,
        -6.97964281e-05+2.57677188e-03j],
       ...,
       [ 2.02029539e-02+0.00000000e+00j, -1.99429931e-02+0.00000000e+00j,
        -2.18848384e-02+0.00000000e+00j, ...,
         1.35060755e-02-1.66402214e-02j, -3.94730102e-02-1.49705900e-02j,
        -3.94730102e-02+1.49705900e-02j],
       [ 3.23333193e-02+0.00000000e+00j,  9.

**Display the transformed data**

In [12]:
data = pd.DataFrame(normalized_dataset1)
data

0         1    2     3    4         5    6         7         8   \
0    0.000000  0.362241  1.0  0.52  1.0  0.736842  0.0  0.048387  0.000000   
1    0.001001  0.227485  1.0  0.00  1.0  0.210526  1.0  0.951613  0.777778   
2    0.002002  0.871915  1.0  0.92  0.0  0.052632  0.0  0.403226  0.888889   
3    0.003003  0.697799  0.0  0.00  1.0  0.947368  1.0  0.370968  0.444444   
4    0.004004  0.623082  0.0  0.36  0.0  0.578947  1.0  0.758065  0.444444   
..        ...       ...  ...   ...  ...       ...  ...       ...       ...   
995  0.995996  0.800534  1.0  0.56  0.0  0.000000  1.0  0.838710  0.444444   
996  0.996997  0.072715  0.0  0.52  1.0  0.000000  0.0  0.177419  0.888889   
997  0.997998  0.456971  0.0  0.36  0.0  0.052632  1.0  0.096774  0.444444   
998  0.998999  0.689126  1.0  0.00  1.0  0.000000  0.0  0.774194  0.333333   
999  1.000000  0.513676  1.0  0.00  0.0  0.210526  1.0  0.532258  0.000000   

           9   ...    11        12        13        14        15        16  \
0    0.941667  ...  0.80  0.118511  0.608550  0.862319  0.500000  0.388889   
1    0.925000  ...  0.60  0.391190  0.237809  0.974772  0.071429  0.000000   
2    0.883333  ...  0.20  0.665967  0.577822  0.572464  0.857143  0.555556   
3    0.133333  ...  1.00  0.154693  0.835671  0.974235  0.357143  0.000000   
4    0.233333  ...  0.90  0.392764  0.206413  0.405260  0.714286  0.444444   
..        ...  ...   ...       ...       ...       ...       ...       ...   
995  0.750000  ...  0.85  0.337703  0.275217  0.498658  0.642857  0.444444   
996  0.883333  ...  0.10  0.604090  0.755511  0.448202  0.214286  0.055556   
997  0.000000  ...  0.60  0.250131  0.216433  0.257649  0.000000  0.000000   
998  0.758333  ...  0.60  0.019927  0.221109  0.602791  0.714286  0.611111   
999  0.500000  ...  0.95  0.239643  0.071476  0.688406  0.285714  0.111111   

           17   18   19   20  
0    0.000000  0.0  1.0  0.0  
1    0.277778  1.0  0.0  0.0  
2    0.444444  0.0  1.0  1.0  
3    0.277778  1.0  1.0  0.0  
4    0.277778  1.0  0.0  1.0  
..        ...  ...  ...  ...  
995  0.722222  1.0  1.0  0.0  
996  0.944444  0.0  1.0  1.0  
997  0.666667  1.0  0.0  0.0  
998  0.222222  0.0  1.0  0.0  
999  0.055556  1.0  0.0  1.0  

[1000 rows x 21 columns]

**Visualize the dataset**

#**Stroke data**

In [13]:
df = pd.read_csv('stroke_data.csv')

In [14]:
df.head()

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [15]:
df.shape

(5110, 12)

**Display the dataset before and after Preprocessing**

In [16]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [17]:
df = df.dropna()

In [18]:
df.shape

(4909, 12)

In [19]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [20]:
df.describe()

id          age  hypertension  heart_disease  \
count   4909.000000  4909.000000   4909.000000    4909.000000   
mean   37064.313506    42.865374      0.091872       0.049501   
std    20995.098457    22.555115      0.288875       0.216934   
min       77.000000     0.080000      0.000000       0.000000   
25%    18605.000000    25.000000      0.000000       0.000000   
50%    37608.000000    44.000000      0.000000       0.000000   
75%    55220.000000    60.000000      0.000000       0.000000   
max    72940.000000    82.000000      1.000000       1.000000   

       avg_glucose_level          bmi       stroke  
count        4909.000000  4909.000000  4909.000000  
mean          105.305150    28.893237     0.042575  
std            44.424341     7.854067     0.201917  
min            55.120000    10.300000     0.000000  
25%            77.070000    23.500000     0.000000  
50%            91.680000    28.100000     0.000000  
75%           113.570000    33.100000     0.000000  
max           271.740000    97.600000     1.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4909 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 4909 non-null   int64  
 1   gender             4909 non-null   object 
 2   age                4909 non-null   float64
 3   hypertension       4909 non-null   int64  
 4   heart_disease      4909 non-null   int64  
 5   ever_married       4909 non-null   object 
 6   work_type          4909 non-null   object 
 7   Residence_type     4909 non-null   object 
 8   avg_glucose_level  4909 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     4909 non-null   object 
 11  stroke             4909 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 498.6+ KB


In [22]:
#df['gender'].unique()
df['gender'] = df['gender'].map({"Male":1,"Female":2,"Other":3})

<ipython-input-22-65602356e4cf>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].map({"Male":1,"Female":2,"Other":3})


In [23]:
#df['ever_married'].unique()
df['ever_married'] = df['ever_married'].map({"Yes":1,"No":2})

In [24]:
#df['work_type'].unique()
df['work_type'] = df['work_type'].map({"Private":1,"Self-employed":2,"Govt_job":3,"children":4,"Never_worked":5})

In [25]:
#df['Residence_type'].unique()
df['Residence_type'] = df['Residence_type'].map({"Urban":1,"Rural":2})

In [26]:
#df['smoking_status'].unique()
df['smoking_status'] = df['smoking_status'].map({"formerly smoked":1,"never smoked":2,"smokes":3,"Unknown":4})

In [27]:
# min-max normalization

from sklearn.preprocessing import MinMaxScaler

# Create an instance of MinMaxScaler
scaler = MinMaxScaler()

# Perform min-max normalization
normalized_dataset2 = scaler.fit_transform(df)

normalized_dataset2

array([[0.12309403, 0.        , 0.81689453, ..., 0.30126002, 0.        ,
        1.        ],
       [0.42593635, 0.        , 0.97558594, ..., 0.25429553, 0.33333333,
        1.        ],
       [0.82490427, 0.5       , 0.59716797, ..., 0.27605956, 0.66666667,
        1.        ],
       ...,
       [0.2696293 , 0.5       , 0.42626953, ..., 0.2325315 , 0.33333333,
        0.        ],
       [0.5142116 , 0.        , 0.62158203, ..., 0.17525773, 0.        ,
        0.        ],
       [0.6121351 , 0.5       , 0.53613281, ..., 0.18213058, 1.        ,
        0.        ]])

**Display Covariance matrix**

In [28]:
covariance_matrix=np.cov(df)
covariance_matrix

array([[6.77708591e+06, 2.33599216e+07, 4.51977365e+07, ...,
        1.48079957e+07, 2.81915736e+07, 3.35559699e+07],
       [2.33599216e+07, 8.05571480e+07, 1.55867696e+08, ...,
        5.10649146e+07, 9.72173507e+07, 1.15722472e+08],
       [4.51977365e+07, 1.55867696e+08, 3.01584836e+08, ...,
        9.88041224e+07, 1.88103359e+08, 2.23908771e+08],
       ...,
       [1.48079957e+07, 5.10649146e+07, 9.88041224e+07, ...,
        3.23699370e+07, 6.16258739e+07, 7.33561037e+07],
       [2.81915736e+07, 9.72173507e+07, 1.88103359e+08, ...,
        6.16258739e+07, 1.17323422e+08, 1.39655345e+08],
       [3.35559699e+07, 1.15722472e+08, 2.23908771e+08, ...,
        7.33561037e+07, 1.39655345e+08, 1.66239080e+08]])

**Display Eigen Values and Eigen Vector**

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

In [ ]:
eigenvalues

In [ ]:
eigenvectors

**Display the transformed data**

In [ ]:
df = pd.DataFrame(normalized_dataset2)
df

**Visualize the dataset**